ALTER USER student_app1 QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO student_app1;
GRANT CREATE TABLE TO student_app1;
GRANT CREATE VIEW TO student_app1;
GRANT CREATE SEQUENCE TO student_app1;
GRANT CREATE PROCEDURE TO student_app1;
GRANT CREATE TRIGGER TO student_app1;
GRANT CREATE SYNONYM TO student_app1;
GRANT CREATE TYPE TO student_app1;
GRANT UNLIMITED TABLESPACE TO student_app1;

GRANT SELECT ANY TABLE TO student_app1;
GRANT INSERT ANY TABLE TO student_app1;
GRANT UPDATE ANY TABLE TO student_app1;
GRANT DELETE ANY TABLE TO student_app1;

GRANT DBA TO student_app1;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'STUDENT_APP1';
SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'STUDENT_APP1';